# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS}
#spring.datasource.driver-class-name=org.postgresql.Driver

# Custom Application Keys
app.jwt.access_token=${ACCESS_TOKEN}
app.jwt.refresh_token=${REFRESH_TOKEN}
next_gen.private.key=${BANK_PRIVATE_KEY}

central_hub_url=${CENTRAL_HUB_URL}
allowed_origins=${ALLOWED_ORIGINS}


# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Performance & Web
spring.threads.virtual.enabled=true
spring.main.lazy-initialization=true

# View Resolver (JSP)
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp




#logging.level.org.springframework.security=DEBUG

# application.properties
#logging.level.org.springframework.transaction=TRACE
#logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG

#spring.jpa.show-sql=true
#logging.level.org.hibernate.orm.jdbc.bind=TRACE


# JPA / Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#what is dialect ?
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect





