# Connection Settings
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
next_gen_bank_secret=${NEXT_GEN_BANK_SECRET}

external.banking.base.url=${BANKING_API_BASE_URL}


management.endpoints.web.exposure.include=metrics
management.metrics.export.defaults.enabled=true

server.port=8081

# Quiet down the main Kafka package
logging.level.org.apache.kafka=WARN
# If you specifically want to hide the massive configuration dumps at startup:
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=WARN
logging.level.org.apache.kafka.clients.producer.ProducerConfig=WARN


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# JPA / Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=validate







